# Eigenvectors and Eigenvalues

In [30]:
import numpy as np
import scipy as sp

In [2]:
A = np.array([[0,1,0],[0,0,1],[4,-17,8]])

In [16]:
eigenValues, eigenVectors =np.linalg.eig(A)

In [17]:
eigenValues

array([0.26794919, 3.73205081, 4.        ])

In [35]:
eigenVectors

array([[-0.96361137, -0.06918418, -0.06052275],
       [-0.25819889, -0.25819889, -0.24209101],
       [-0.06918418, -0.96361137, -0.96836405]])

In [19]:
np.poly(A)

array([ 1., -8., 17., -4.])

In [23]:
eigenValues[0]

0.26794919243112236

In [34]:
lambdas = eigenValues * np.eye(3)

sp.linalg.null(lambdas[2]-A)

AttributeError: 'module' object has no attribute 'linalg'