# Gram-Schmidt Process for orthonormalising a matrix

> The Gram–Schmidt process is a method for orthonormalising a set of vectors in an inner product space

[Wikipedia](https://en.wikipedia.org/wiki/Gram%E2%80%93Schmidt_process)

# Setup

In [2]:
import numpy as np

# QR decomposition

In [3]:
def gram_schmidt(A):
    """Orthogonalize a set of vectors stored as the columns of matrix A."""
    # Get the number of vectors.
    n = A.shape[1]
    for j in range(n):
        # To orthogonalize the vector in column j with respect to the
        # previous vectors, subtract from it its projection onto
        # each of the previous vectors.
        for k in range(j):
            A[:, j] -= np.dot(A[:, k], A[:, j]) * A[:, k]
        A[:, j] = A[:, j] / np.linalg.norm(A[:, j])
    return A

In [4]:
def gs(A):
    n = A.shape[1] # Get the number of columns
    for j in range(n):
        for k in range(j):
                A[:,j]-= np.dot(A[:, k], A[:, j]) * A[:, k]/(np.linalg.norm(A[:,k])**2)
    return A
        

In [5]:
test = np.array([[1.0, 1.0], [1.0, 3.0], [2.0, -1.0]])
test2 = np.array([[1.0, 1.0], [1.0, 3.0], [2.0, -1.0]])
q=np.linalg.qr(test)[0]
print(np.transpose(q))
print(np.transpose(gram_schmidt(test)))
print(np.transpose(gs(test2)))

[[-0.40824829 -0.40824829 -0.81649658]
 [-0.20739034 -0.82956136  0.51847585]]
[[ 0.40824829  0.40824829  0.81649658]
 [ 0.20739034  0.82956136 -0.51847585]]
[[ 1.          1.          2.        ]
 [ 0.66666667  2.66666667 -1.66666667]]


In [9]:
np.dot(np.transpose(test[1]),np.transpose(test2[0]))

0.9612891943200899

In [7]:
np.dot(np.transpose(test)[1],np.transpose(test)[0])

-1.1102230246251565e-16

In [10]:
test.shape

(3, 2)

In [29]:
wMatrix = np.array([[1.0,5.0,-7.0],[0.0,3.0,2.0]])

In [25]:
np.linalg.qr(np.transpose(wMatrix))[0]

array([[-0.11547005,  0.0036999 ],
       [-0.57735027, -0.81397782],
       [ 0.80829038, -0.58088417]])

In [30]:
gs(np.transpose(wMatrix))

array([[ 1.        , -0.01333333],
       [ 5.        ,  2.93333333],
       [-7.        ,  2.09333333]])

In [27]:
gram_schmidt(np.transpose(wMatrix))

array([[ 0.11547005, -0.0036999 ],
       [ 0.57735027,  0.81397782],
       [-0.80829038,  0.58088417]])

In [31]:
wMatrix

array([[ 1.        ,  5.        , -7.        ],
       [-0.01333333,  2.93333333,  2.09333333]])

In [36]:
np.invert(wMatrix.T)

TypeError: ufunc 'invert' not supported for the input types, and the inputs could not be safely coerced to any supported types according to the casting rule ''safe''

In [43]:
np.linalg.pinv(wMatrix)

array([[ 0.01333333, -0.00102669],
       [ 0.06666667,  0.22587269],
       [-0.09333333,  0.16119097]])

In [44]:
matrix02= np.array([[1.0,0.0,0.0],[5.0,3.0,1.0],[-7.0,2.0,0],[3.0,3.0,-2.0],[3.0,3.0,7.0]])

In [45]:
gs(matrix02)

array([[ 1.        , -0.20430108, -0.11022998],
       [ 5.        ,  1.97849462, -1.09040444],
       [-7.        ,  3.43010753, -0.25455987],
       [ 3.        ,  2.38709677, -3.86994449],
       [ 3.        ,  2.38709677,  5.13005551]])

In [51]:
b = np.array([[1],[2],[3],[3],[3]])

In [52]:
b

array([[1],
       [2],
       [3],
       [3],
       [3]])

In [60]:
np.matmul(np.matmul(np.matmul(np.transpose(matrix02),matrix02),np.transpose(matrix02)),b)

array([[744.        ],
       [769.22603769],
       [ 30.88206495]])

In [ ]:
plt