# Diagonalization and symmetry

In [1]:
import numpy as np

In [17]:
A = np.array([[4,2,2],[2,4,2],[2,2,4]])

In [13]:
np.matmul(A,np.transpose(A))

array([[24, 20, 20],
       [20, 24, 20],
       [20, 20, 24]])

In [18]:
eigenValues, eigenVectors = np.linalg.eig(A)

In [19]:
eigenValues

array([2., 8., 2.])

In [20]:
eigenVectors

array([[-0.81649658,  0.57735027, -0.32444284],
       [ 0.40824829,  0.57735027, -0.48666426],
       [ 0.40824829,  0.57735027,  0.81110711]])

In [21]:
np.matmul(eigenVectors,np.transpose(eigenVectors))

array([[ 1.10526316,  0.15789474, -0.26315789],
       [ 0.15789474,  0.73684211,  0.10526316],
       [-0.26315789,  0.10526316,  1.15789474]])